[package]
name = "custody_rsa"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
rsa = "0.9.0"
openssl = "0.10"
base64-url = "3.0.0"
pem = "3.0.3"

[lib]
name = "custody_rsa"
crate-type = ["cdylib"]

